# Generated by Django 3.2.16 on 2023-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gitlab_Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(help_text=' ', max_length=255, verbose_name='repository name')),
                ('repo_url', models.CharField(help_text=' ', max_length=255, verbose_name='repository url')),
                ('object_kind', models.CharField(help_text='push, tag_push, issue, note', max_length=255, verbose_name='object_kind value')),
                ('project_id', models.IntegerField(default=0, help_text='Your project id in gitlab', verbose_name='project_id value')),
                ('http_x_gitlab_event', models.CharField(help_text='Push Hook, Tag Push Hook, Issue Hook, Note Hook', max_length=255, verbose_name='X-Gitlab-Event in request header')),
            ],
        ),
    ]
