# Generated by Django 3.2.16 on 2023-03-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='credential',
        ),
    ]
